// Korean vocabulary dataset (Korean → Bahasa Indonesia)
// kr : Korean word
// rom: romanization (Revised Romanization)
// id : correct Indonesian meaning
// wrong: 3 plausible distractors (never equal to any correct answer in this set)

const WORDS = [
  { kr: "경우",      rom: "gyeong-u",     id: "kasus/situasi",   wrong: ["alasan", "cara", "pengaruh"] },
  { kr: "이유",      rom: "iyu",          id: "alasan",          wrong: ["hasil", "ciri", "gaya"] },
  { kr: "방법",      rom: "bangbeop",     id: "cara",            wrong: ["hasil", "warna", "bentuk"] },
  { kr: "영향",      rom: "yeonghyang",   id: "pengaruh",        wrong: ["hasil", "gaya", "risiko"] },
  { kr: "문제",      rom: "munje",        id: "masalah",         wrong: ["topik", "contoh", "sapaan"] },
  { kr: "시간",      rom: "sigan",        id: "waktu",           wrong: ["tanggal", "jadwal", "umur"] },
  { kr: "장소",      rom: "jangso",       id: "tempat",          wrong: ["kota", "desa", "gedung"] },
  { kr: "사람",      rom: "saram",        id: "orang",           wrong: ["hewan", "tumbuhan", "benda"] },
  { kr: "물",        rom: "mul",          id: "air",             wrong: ["es", "kabut", "pasir"] },
  { kr: "불",        rom: "bul",          id: "api",             wrong: ["es", "kabut", "awan"] },
  { kr: "산",        rom: "san",          id: "gunung",          wrong: ["sungai", "hutan", "lembah"] },
  { kr: "바다",      rom: "bada",         id: "laut",            wrong: ["sungai", "danau", "lembah"] },
  { kr: "하늘",      rom: "haneul",       id: "langit",          wrong: ["bumi", "awan", "bintang"] },
  { kr: "땅",        rom: "ttang",        id: "tanah",           wrong: ["batu", "pasir", "lumut"] },
  { kr: "나무",      rom: "namu",         id: "pohon",           wrong: ["rumput", "biji", "akar"] },
  { kr: "꽃",        rom: "kkot",         id: "bunga",           wrong: ["daun", "biji", "rumput"] },
  { kr: "새",        rom: "sae",          id: "burung",          wrong: ["ikan", "kuda", "serangga"] },
  { kr: "개",        rom: "gae",          id: "anjing",          wrong: ["kelinci", "kuda", "tikus"] },
  { kr: "고양이",    rom: "goyangi",      id: "kucing",          wrong: ["tikus", "kelinci", "kuda"] },
  { kr: "집",        rom: "jip",          id: "rumah",           wrong: ["kantor", "sekolah", "toko"] },
  { kr: "문",        rom: "mun",          id: "pintu",           wrong: ["jendela", "dinding", "atap"] },
  { kr: "길",        rom: "gil",          id: "jalan",           wrong: ["lorong", "pagar", "jembatan"] },
  { kr: "자동차",    rom: "jadongcha",    id: "mobil",           wrong: ["sepeda", "truk", "kapal"] },
  { kr: "기차",      rom: "gicha",        id: "kereta",          wrong: ["bus", "kapal", "helikopter"] },
  { kr: "비행기",    rom: "bihaenggi",    id: "pesawat",         wrong: ["kapal", "helikopter", "truk"] },
  { kr: "아침",      rom: "achim",        id: "pagi",            wrong: ["senja", "larut malam", "subuh"] },
  { kr: "저녁",      rom: "jeonyeok",     id: "petang",          wrong: ["subuh", "siang", "dini hari"] },
  { kr: "오늘",      rom: "oneul",        id: "hari ini",        wrong: ["tadi malam", "pekan lalu", "lusa"] },
  { kr: "내일",      rom: "naeil",        id: "besok",           wrong: ["lusa", "tadi malam", "pekan lalu"] },
  { kr: "어제",      rom: "eoeje",        id: "kemarin",         wrong: ["lusa", "tadi malam", "nanti"] },
  { kr: "주말",      rom: "jumal",        id: "akhir pekan",     wrong: ["hari kerja", "hari raya", "hari libur"] },
  { kr: "가족",      rom: "gajok",        id: "keluarga",        wrong: ["tetangga", "rekan", "kenalan"] },
  { kr: "어머니",    rom: "eomeoni",      id: "ibu",             wrong: ["keponakan", "nenek", "bibi"] },
  { kr: "아버지",    rom: "abeoji",       id: "ayah",            wrong: ["paman", "kakek", "keponakan"] },
  { kr: "친구",      rom: "chingu",       id: "teman",           wrong: ["tetangga", "kenalan", "rekan"] },
  { kr: "선생님",    rom: "seonsaengnim", id: "guru",            wrong: ["petani", "insinyur", "perawat"] },
  { kr: "학생",      rom: "haksaeng",     id: "siswa",           wrong: ["petani", "nelayan", "insinyur"] },
  { kr: "의사",      rom: "uisa",         id: "dokter",          wrong: ["petani", "nelayan", "perawat"] },
  { kr: "회사",      rom: "hoesa",        id: "perusahaan",      wrong: ["sekolah", "toko", "pabrik"] },
  { kr: "돈",        rom: "don",          id: "uang",            wrong: ["pajak", "kualitas", "nilai"] },
  { kr: "가격",      rom: "gageuk",       id: "harga",           wrong: ["biaya", "pajak", "diskon"] },
  { kr: "시장",      rom: "sijang",       id: "pasar",           wrong: ["toko", "restoran", "stasiun"] },
  { kr: "질문",      rom: "jilmun",       id: "pertanyaan",      wrong: ["sapaan", "keluhan", "pujian"] },
  { kr: "대답",      rom: "daedap",       id: "jawaban",         wrong: ["sapaan", "keluhan", "pujian"] },
  { kr: "이야기",    rom: "iyagi",        id: "cerita",          wrong: ["puisi", "gambar", "surat"] },
  { kr: "노래",      rom: "norae",        id: "lagu",            wrong: ["puisi", "gambar", "tari"] },
  { kr: "영화",      rom: "yeonghwa",     id: "film",            wrong: ["koran", "gambar", "novel"] },
  { kr: "책",        rom: "chaek",        id: "buku",            wrong: ["koran", "majalah", "novel"] },
  { kr: "마음",      rom: "maeum",        id: "hati",            wrong: ["perut", "telinga", "punggung"] },
  { kr: "기분",      rom: "gibun",        id: "suasana hati",    wrong: ["penampilan", "kesehatan", "umur"] },
  { kr: "날씨",      rom: "nalssi",       id: "cuaca",           wrong: ["tanggal", "jadwal", "umur"] },
  { kr: "계절",      rom: "gyejeol",      id: "musim",           wrong: ["tanggal", "jadwal", "tahun"] },
  { kr: "옷",        rom: "ot",           id: "pakaian",         wrong: ["topi", "kacamata", "syal"] },
  { kr: "신발",      rom: "sinbal",       id: "sepatu",          wrong: ["topi", "sarung tangan", "kaus kaki"] },
  { kr: "머리",      rom: "meori",        id: "kepala",          wrong: ["perut", "punggung", "lutut"] },
  { kr: "발",        rom: "bal",          id: "kaki",            wrong: ["tangan", "punggung", "siku"] },
  { kr: "목소리",    rom: "moksori",      id: "suara",           wrong: ["warna", "bau", "tekstur"] },
  { kr: "약",        rom: "yak",          id: "obat",            wrong: ["perban", "suplemen", "vitamin"] },
  { kr: "병원",      rom: "byeongwon",    id: "rumah sakit",     wrong: ["apotek", "klinik", "toko"] },
  { kr: "경찰",      rom: "gyeongchal",   id: "polisi",          wrong: ["tentara", "penjaga", "petani"] },
  { kr: "목표",      rom: "mokpyo",       id: "tujuan",          wrong: ["proses", "risiko", "hadiah"] },
  { kr: "기회",      rom: "gihoe",        id: "kesempatan",      wrong: ["risiko", "kewajiban", "hambatan"] }
];

// Indonesian → Korean lookup for EVERY option (correct + distractors),
// so after an answer each option can show its Korean counterpart.
const KO = {
  // --- correct answers ---
  "kasus/situasi": "경우",
  "alasan": "이유",
  "cara": "방법",
  "pengaruh": "영향",
  "masalah": "문제",
  "waktu": "시간",
  "tempat": "장소",
  "orang": "사람",
  "air": "물",
  "api": "불",
  "gunung": "산",
  "laut": "바다",
  "langit": "하늘",
  "tanah": "땅",
  "pohon": "나무",
  "bunga": "꽃",
  "burung": "새",
  "anjing": "개",
  "kucing": "고양이",
  "rumah": "집",
  "pintu": "문",
  "jalan": "길",
  "mobil": "자동차",
  "kereta": "기차",
  "pesawat": "비행기",
  "pagi": "아침",
  "petang": "저녁",
  "hari ini": "오늘",
  "besok": "내일",
  "kemarin": "어제",
  "akhir pekan": "주말",
  "keluarga": "가족",
  "ibu": "어머니",
  "ayah": "아버지",
  "teman": "친구",
  "guru": "선생님",
  "siswa": "학생",
  "dokter": "의사",
  "perusahaan": "회사",
  "uang": "돈",
  "harga": "가격",
  "pasar": "시장",
  "pertanyaan": "질문",
  "jawaban": "대답",
  "cerita": "이야기",
  "lagu": "노래",
  "film": "영화",
  "buku": "책",
  "hati": "마음",
  "suasana hati": "기분",
  "cuaca": "날씨",
  "musim": "계절",
  "pakaian": "옷",
  "sepatu": "신발",
  "kepala": "머리",
  "kaki": "발",
  "suara": "목소리",
  "obat": "약",
  "rumah sakit": "병원",
  "polisi": "경찰",
  "tujuan": "목표",
  "kesempatan": "기회",

  // --- distractors ---
  "hasil": "결과",
  "ciri": "특징",
  "gaya": "스타일",
  "warna": "색깔",
  "bentuk": "모양",
  "ukuran": "크기",
  "topik": "주제",
  "contoh": "예시",
  "sapaan": "인사말",
  "tanggal": "날짜",
  "jadwal": "일정",
  "umur": "나이",
  "kota": "도시",
  "desa": "마을",
  "gedung": "건물",
  "hewan": "동물",
  "tumbuhan": "식물",
  "benda": "물건",
  "es": "얼음",
  "kabut": "안개",
  "pasir": "모래",
  "awan": "구름",
  "sungai": "강",
  "hutan": "숲",
  "lembah": "계곡",
  "danau": "호수",
  "bumi": "지구",
  "bintang": "별",
  "batu": "돌",
  "lumut": "이끼",
  "rumput": "풀",
  "biji": "씨앗",
  "akar": "뿌리",
  "daun": "잎",
  "ikan": "물고기",
  "kuda": "말",
  "serangga": "곤충",
  "kelinci": "토끼",
  "tikus": "쥐",
  "kantor": "사무실",
  "sekolah": "학교",
  "toko": "가게",
  "jendela": "창문",
  "dinding": "벽",
  "atap": "지붕",
  "lorong": "복도",
  "pagar": "울타리",
  "jembatan": "다리",
  "sepeda": "자전거",
  "truk": "트럭",
  "kapal": "배",
  "bus": "버스",
  "helikopter": "헬리콥터",
  "senja": "노을",
  "larut malam": "늦은 밤",
  "subuh": "새벽",
  "siang": "낮",
  "dini hari": "심야",
  "tadi malam": "어젯밤",
  "pekan lalu": "지난주",
  "lusa": "모레",
  "nanti": "나중에",
  "hari kerja": "평일",
  "hari raya": "공휴일",
  "hari libur": "휴일",
  "hari biasa": "평일",
  "tetangga": "이웃",
  "rekan": "동료",
  "kenalan": "지인",
  "nenek": "할머니",
  "bibi": "고모",
  "paman": "삼촌",
  "kakek": "할아버지",
  "keponakan": "조카",
  "petani": "농부",
  "nelayan": "어부",
  "insinyur": "엔지니어",
  "perawat": "간호사",
  "pabrik": "공장",
  "pajak": "세금",
  "kualitas": "품질",
  "nilai": "가치",
  "biaya": "비용",
  "diskon": "할인",
  "restoran": "식당",
  "stasiun": "기차역",
  "keluhan": "불만",
  "pujian": "칭찬",
  "puisi": "시",
  "gambar": "그림",
  "surat": "편지",
  "koran": "신문",
  "majalah": "잡지",
  "novel": "소설",
  "perut": "배",
  "telinga": "귀",
  "punggung": "등",
  "penampilan": "외모",
  "kesehatan": "건강",
  "tahun": "해",
  "syal": "목도리",
  "sarung tangan": "장갑",
  "kaus kaki": "양말",
  "lutut": "무릎",
  "tangan": "손",
  "siku": "팔꿈치",
  "tekstur": "질감",
  "vitamin": "비타민",
  "suplemen": "영양제",
  "apotek": "약국",
  "klinik": "클리닉",
  "tentara": "군인",
  "penjaga": "경비원",
  "proses": "과정",
  "risiko": "위험",
  "hadiah": "선물",
  "kewajiban": "의무",
  "hambatan": "장애물",

  // --- extras (distractors used by a few entries) ---
  "tari": "춤",
  "topi": "모자",
  "kacamata": "안경",
  "bau": "냄새",
  "perban": "붕대",
  "ukuran": "크기"
};

// ---------------------------------------------------------------------------
// Kosakata dari PDF "Kosakata level dasar (BAB 1-5)" dan
// "Kosakata Level menengah (BAB 1-5)".
// Entri baru memakai `cat` (kategori) menggantikan daftar `wrong` —
// app.js membuat 3 pilihan pengganggu dari topik yang sama.
// ---------------------------------------------------------------------------
const WORDS_EXTRA = [
  // 1. Salam & Ekspresi
  { kr: "안녕하세요",     rom: "annyeonghaseyo",   id: "halo / selamat pagi/siang/malam", cat: "ekspresi" },
  { kr: "안녕히 계세요",  rom: "annyeonghi gyeseyo", id: "selamat tinggal (yang pergi)",   cat: "ekspresi" },
  { kr: "안녕히 가세요",  rom: "annyeonghi gaseyo",  id: "selamat jalan",                  cat: "ekspresi" },
  { kr: "죄송합니다",     rom: "joesonghamnida",    id: "maaf (formal)",                  cat: "ekspresi" },
  { kr: "괜찮습니다",     rom: "gwaenchanhamnida",  id: "tidak apa-apa",                  cat: "ekspresi" },
  { kr: "감사합니다",     rom: "gamsahamnida",      id: "terima kasih",                   cat: "ekspresi" },
  { kr: "고맙습니다",     rom: "gomapseumnida",     id: "terima kasih (lebih santai)",    cat: "ekspresi" },
  { kr: "아닙니다",       rom: "animnida",          id: "bukan / tidak / terima kasih kembali", cat: "ekspresi" },
  { kr: "실례합니다",     rom: "sillyehamnida",     id: "permisi",                        cat: "ekspresi" },
  { kr: "주말 잘 보내세요", rom: "jumal jal bonaeseyo", id: "selamat menikmati akhir pekan", cat: "ekspresi" },

  // 2. Kata Kerja
  { kr: "만나다",   rom: "man-na-da",      id: "bertemu",                     cat: "kerja" },
  { kr: "뵙다",     rom: "bop-da",         id: "bertemu (bentuk hormat)",     cat: "kerja" },
  { kr: "보내다",   rom: "bonaeda",        id: "menghabiskan / mengirim",     cat: "kerja" },
  { kr: "말하다",   rom: "malhada",        id: "berbicara / mengatakan",      cat: "kerja" },
  { kr: "읽다",     rom: "ik-da",          id: "membaca",                     cat: "kerja" },
  { kr: "듣다",     rom: "deud-da",        id: "mendengar",                   cat: "kerja" },
  { kr: "묻다",     rom: "mud-da",         id: "bertanya",                    cat: "kerja" },
  { kr: "대답하다", rom: "daedap-hada",    id: "menjawab",                    cat: "kerja" },
  { kr: "선택하다", rom: "seontaek-hada",  id: "memilih",                     cat: "kerja" },
  { kr: "들어가다", rom: "deureo-gada",    id: "masuk",                       cat: "kerja" },
  { kr: "열다",     rom: "yeol-da",        id: "membuka",                     cat: "kerja" },
  { kr: "나누다",   rom: "nanu-da",        id: "membagi",                     cat: "kerja" },
  { kr: "살다",     rom: "sal-da",         id: "tinggal / hidup",             cat: "kerja" },
  { kr: "팔다",     rom: "pal-da",         id: "menjual",                     cat: "kerja" },
  { kr: "사용하다", rom: "sayong-hada",    id: "menggunakan",                 cat: "kerja" },
  { kr: "받다",     rom: "bat-da",         id: "mendapatkan",                 cat: "kerja" },
  { kr: "찾다",     rom: "chat-da",        id: "mendapatkan / mencari",       cat: "kerja" },
  { kr: "일하다",   rom: "ilhada",         id: "bekerja",                     cat: "kerja" },
  { kr: "공부하다", rom: "gongbu-hada",    id: "belajar",                     cat: "kerja" },
  { kr: "운동하다", rom: "undong-hada",    id: "berolahraga",                 cat: "kerja" },
  { kr: "전화하다", rom: "jeonhwa-hada",   id: "menelepon",                   cat: "kerja" },
  { kr: "요리하다", rom: "yori-hada",      id: "memasak",                     cat: "kerja" },
  { kr: "쇼핑하다", rom: "syoping-hada",   id: "berbelanja",                  cat: "kerja" },
  { kr: "쉬다",     rom: "swi-da",         id: "beristirahat",                cat: "kerja" },
  { kr: "자다",     rom: "ja-da",          id: "tidur",                       cat: "kerja" },
  { kr: "가다",     rom: "ga-da",          id: "pergi",                       cat: "kerja" },
  { kr: "오다",     rom: "o-da",           id: "datang",                      cat: "kerja" },
  { kr: "하다",     rom: "ha-da",          id: "melakukan",                   cat: "kerja" },
  { kr: "먹다",     rom: "meok-da",        id: "makan",                       cat: "kerja" },
  { kr: "보다",     rom: "bo-da",          id: "melihat / menonton",          cat: "kerja" },
  { kr: "앉다",     rom: "an-da",          id: "duduk",                       cat: "kerja" },
  { kr: "주다",     rom: "ju-da",          id: "memberi",                     cat: "kerja" },
  { kr: "벗다",     rom: "beot-da",        id: "melepas",                     cat: "kerja" },
  { kr: "생활하다", rom: "saenghal-hada",  id: "tinggal / menjalani kehidupan", cat: "kerja" },
  { kr: "사다",     rom: "sa-da",          id: "membeli",                     cat: "kerja" },

  // 3. Kata Sifat
  { kr: "반갑다",   rom: "ban-gap-da",     id: "senang (bertemu)",            cat: "sifat" },
  { kr: "많다",     rom: "man-da",         id: "banyak",                      cat: "sifat" },
  { kr: "높다",     rom: "nop-da",         id: "tinggi",                      cat: "sifat" },
  { kr: "어리다",   rom: "eori-da",        id: "muda",                        cat: "sifat" },
  { kr: "친하다",   rom: "chinhada",       id: "akrab",                       cat: "sifat" },
  { kr: "가볍다",   rom: "gabyeo-da",      id: "ringan",                      cat: "sifat" },
  { kr: "다르다",   rom: "dareu-da",       id: "berbeda",                     cat: "sifat" },
  { kr: "같다",     rom: "gat-da",         id: "sama",                        cat: "sifat" },
  { kr: "알맞다",   rom: "almap-da",       id: "sesuai / cocok",              cat: "sifat" },
  { kr: "길다",     rom: "gil-da",         id: "panjang",                     cat: "sifat" },
  { kr: "젊다",     rom: "jeol-da",        id: "muda (usia dewasa)",          cat: "sifat" },

  // 4. Kata Benda Umum
  { kr: "이름",     rom: "ireum",          id: "nama",                        cat: "benda" },
  { kr: "나라",     rom: "nara",           id: "negara",                      cat: "benda" },
  { kr: "처음",     rom: "cheoeum",        id: "pertama / awal",              cat: "benda" },
  { kr: "회사원",   rom: "hoesawon",       id: "karyawan perusahaan",         cat: "benda" },
  { kr: "근로자",   rom: "geunroja",       id: "pekerja / buruh",             cat: "benda" },
  { kr: "목수",     rom: "moksu",          id: "tukang kayu",                 cat: "benda" },
  { kr: "농부",     rom: "nongbu",         id: "petani",                      cat: "benda" },
  { kr: "남자",     rom: "namja",          id: "laki-laki",                   cat: "benda" },
  { kr: "여자",     rom: "yeoja",          id: "perempuan",                   cat: "benda" },
  { kr: "손",       rom: "son",            id: "tangan",                      cat: "benda" },
  { kr: "허리",     rom: "heori",          id: "pinggang",                    cat: "benda" },
  { kr: "고개",     rom: "gogae",          id: "kepala (bagian atas / tengkuk)", cat: "benda" },
  { kr: "글",       rom: "geul",           id: "tulisan / teks",              cat: "benda" },
  { kr: "내용",     rom: "naeyong",        id: "isi / konten",                cat: "benda" },
  { kr: "고향",     rom: "gohyang",        id: "kampung halaman",             cat: "benda" },
  { kr: "동사",     rom: "dongsa",         id: "kata kerja",                  cat: "benda" },

  // 7. Benda di Kantor / Sekitar Kita
  { kr: "사무실",   rom: "samusil",        id: "kantor",                      cat: "benda" },
  { kr: "물건",     rom: "mulgeon",        id: "barang",                      cat: "benda" },

  // 8. Benda Rumah Tangga & Lainnya
  { kr: "지갑",     rom: "jib",            id: "dompet",                      cat: "benda" },
  { kr: "열쇠",     rom: "yeolsoe",        id: "kunci",                       cat: "benda" },
  { kr: "가방",     rom: "gabang",         id: "tas",                         cat: "benda" },
  { kr: "우산",     rom: "usan",           id: "payung",                      cat: "benda" },
  { kr: "화장품",   rom: "hwajangpum",     id: "kosmetik",                    cat: "benda" },
  { kr: "거울",     rom: "geoul",          id: "cermin",                      cat: "benda" },
  { kr: "빗",       rom: "bit",            id: "sisir",                       cat: "benda" },
  { kr: "베개",     rom: "begae",          id: "bantal",                      cat: "benda" },
  { kr: "이불",     rom: "ibul",           id: "selimut",                     cat: "benda" },
  { kr: "쇠",       rom: "soe",            id: "logam",                       cat: "benda" },
  { kr: "에어컨",   rom: "e-eokeon",       id: "AC",                          cat: "benda" },
  { kr: "침대",     rom: "chimdae",        id: "tempat tidur",                cat: "benda" },
  { kr: "의자",     rom: "uija",           id: "kursi",                       cat: "benda" },
  { kr: "책상",     rom: "chaeksang",      id: "meja tulis",                  cat: "benda" },
  { kr: "옷장",     rom: "otjang",         id: "lemari pakaian",              cat: "benda" },
  { kr: "소파",     rom: "sopa",           id: "sofa",                        cat: "benda" },
  { kr: "텔레비전", rom: "telrebi-jeon",   id: "televisi",                    cat: "benda" },
  { kr: "전자레인지", rom: "jeonjareinji",  id: "microwave",                   cat: "benda" },
  { kr: "세탁기",   rom: "setakgi",        id: "mesin cuci",                  cat: "benda" },
  { kr: "냉장고",   rom: "naengjanggo",    id: "lemari es",                   cat: "benda" },
  { kr: "청소기",   rom: "cheongsogi",     id: "penyedot debu",               cat: "benda" },

  // 5. Kata Tanya & Lainnya
  { kr: "어느",     rom: "eoneu",          id: "yang mana",                   cat: "tanya" },
  { kr: "무엇",     rom: "mueot",          id: "apa",                         cat: "tanya" },
  { kr: "뭐",       rom: "mwo",            id: "apa (bentuk santai)",         cat: "tanya" },
  { kr: "네",       rom: "ne",             id: "ya",                          cat: "tanya" },
  { kr: "아니요",   rom: "aniyo",          id: "tidak",                       cat: "tanya" },
  { kr: "저",       rom: "jeo",            id: "saya (rendah hati)",          cat: "tanya" },
  { kr: "잘",       rom: "jal",            id: "dengan baik",                 cat: "tanya" },
  { kr: "살",       rom: "sal",            id: "tahun (satuan umur)",         cat: "tanya" },
  { kr: "다음",     rom: "daeum",          id: "berikut / selanjutnya",       cat: "tanya" },
  { kr: "도",       rom: "do",             id: "juga",                        cat: "tanya" },
  { kr: "지금",     rom: "jigeum",         id: "sekarang",                    cat: "tanya" },
  { kr: "너무",     rom: "neomu",          id: "terlalu / sangat",            cat: "tanya" },
  { kr: "함께",     rom: "hamkke",         id: "bersama",                     cat: "tanya" },
  { kr: "서로",     rom: "sero",           id: "sesama",                      cat: "tanya" },
  { kr: "쉽게",     rom: "swipge",         id: "dengan mudah",                cat: "tanya" },
  { kr: "밖에",     rom: "baekke",         id: "luar",                        cat: "tanya" },
  { kr: "빈 곳",    rom: "bin got",        id: "tempat kosong",               cat: "tanya" },

  // 6. Nama Negara
  { kr: "한국",       rom: "hanguk",              id: "Korea Selatan",   cat: "negara" },
  { kr: "네팔",       rom: "nepal",               id: "Nepal",           cat: "negara" },
  { kr: "동티모르",   rom: "dong-timo-reu",       id: "Timor Leste",     cat: "negara" },
  { kr: "라오스",     rom: "raoseu",              id: "Laos",            cat: "negara" },
  { kr: "몽골",       rom: "mong-gol",            id: "Mongolia",        cat: "negara" },
  { kr: "미얀마",     rom: "mi-yan-ma",           id: "Myanmar",         cat: "negara" },
  { kr: "방글라데시", rom: "bang-geul-la-deu-si", id: "Bangladesh",      cat: "negara" },
  { kr: "베트남",     rom: "be-teu-nam",          id: "Vietnam",         cat: "negara" },
  { kr: "스리랑카",   rom: "seu-ri-lang-ka",      id: "Sri Lanka",       cat: "negara" },
  { kr: "우즈베키스탄", rom: "u-ju-beu-ki-seu-tan", id: "Uzbekistan",     cat: "negara" },
  { kr: "인도네시아", rom: "in-do-ne-si-a",       id: "Indonesia",       cat: "negara" },
  { kr: "중국",       rom: "jung-guk",            id: "Tiongkok",        cat: "negara" },
  { kr: "캄보디아",   rom: "kam-bo-di-a",         id: "Kamboja",         cat: "negara" },
  { kr: "키르기스스탄", rom: "ki-reu-gi-seu-seu-tan", id: "Kirgizstan",   cat: "negara" },
  { kr: "타지키스탄", rom: "ta-ji-ki-seu-tan",    id: "Tajikistan",      cat: "negara" },
  { kr: "태국",       rom: "tae-guk",             id: "Thailand",        cat: "negara" },
  { kr: "파키스탄",   rom: "pa-ki-seu-tan",       id: "Pakistan",        cat: "negara" },
  { kr: "필리핀",     rom: "pil-li-pin",          id: "Filipina",        cat: "negara" },

  // 9. Tempat Umum
  { kr: "식당",     rom: "sikdang",        id: "restoran",                   cat: "tempat" },
  { kr: "은행",     rom: "eunhaeng",       id: "bank",                       cat: "tempat" },
  { kr: "커피숍",   rom: "keopisyop",      id: "kedai kopi",                 cat: "tempat" },
  { kr: "편의점",   rom: "pyeonuijeom",    id: "minimarket",                 cat: "tempat" },
  { kr: "미용실",   rom: "miyongsil",      id: "salon",                      cat: "tempat" },
  { kr: "슈퍼마켓", rom: "syupeomaket",    id: "supermarket",                cat: "tempat" },
  { kr: "약국",     rom: "yakguk",         id: "apotek",                     cat: "tempat" },
  { kr: "우체국",   rom: "ucheguk",        id: "kantor pos",                 cat: "tempat" },
  { kr: "여기",     rom: "yeogi",          id: "di sini",                    cat: "tempat" },
  { kr: "거기",     rom: "geogi",          id: "di situ",                    cat: "tempat" },
  { kr: "저기",     rom: "jeogi",          id: "di sana",                    cat: "tempat" },
  { kr: "어디",     rom: "eodi",           id: "di mana",                    cat: "tempat" },
  { kr: "기숙사",   rom: "gisuksa",        id: "asrama",                     cat: "tempat" },
  { kr: "영화관",   rom: "yeonghwagwan",   id: "bioskop",                    cat: "tempat" },

  // 10. Hari & Waktu
  { kr: "요일",     rom: "yoil",           id: "hari (dalam minggu)",        cat: "waktu" },
  { kr: "월요일",   rom: "wolyoil",        id: "Senin",                      cat: "waktu" },
  { kr: "화요일",   rom: "hwayoil",        id: "Selasa",                     cat: "waktu" },
  { kr: "수요일",   rom: "suyoil",         id: "Rabu",                       cat: "waktu" },
  { kr: "목요일",   rom: "mokyoil",        id: "Kamis",                      cat: "waktu" },
  { kr: "금요일",   rom: "geumyoil",       id: "Jumat",                      cat: "waktu" },
  { kr: "토요일",   rom: "toyoil",         id: "Sabtu",                      cat: "waktu" },
  { kr: "일요일",   rom: "ilyoil",         id: "Minggu",                     cat: "waktu" },
  { kr: "평일",     rom: "pyeongil",       id: "hari kerja",                 cat: "waktu" },
  { kr: "매일",     rom: "maeil",          id: "setiap hari",                cat: "waktu" },
  { kr: "날짜",     rom: "naljja",         id: "tanggal",                    cat: "waktu" },
  { kr: "1월",      rom: "ilwol",          id: "Januari",                    cat: "waktu" },
  { kr: "2월",      rom: "iwol",           id: "Februari",                   cat: "waktu" },
  { kr: "3월",      rom: "samwol",         id: "Maret",                      cat: "waktu" },
  { kr: "4월",      rom: "sawol",          id: "April",                      cat: "waktu" },
  { kr: "5월",      rom: "owol",           id: "Mei",                        cat: "waktu" },
  { kr: "6월",      rom: "yukwol",         id: "Juni",                       cat: "waktu" },
  { kr: "7월",      rom: "chilwol",        id: "Juli",                       cat: "waktu" },
  { kr: "8월",      rom: "palwol",         id: "Agustus",                    cat: "waktu" },
  { kr: "9월",      rom: "guwol",          id: "September",                  cat: "waktu" },
  { kr: "10월",     rom: "sipwol",         id: "Oktober",                    cat: "waktu" },
  { kr: "11월",     rom: "sip-ilwol",      id: "November",                   cat: "waktu" },
  { kr: "12월",     rom: "sip-iwol",       id: "Desember",                   cat: "waktu" },
  { kr: "지난주",   rom: "jinanju",        id: "minggu lalu",                cat: "waktu" }
];

WORDS.push.apply(WORDS, WORDS_EXTRA);

// Extra batch: greetings/etiquette, connectors, jobs, shopping, cities, transport, culture, holidays.
const WORDS_EXTRA2 = [
  { kr: "인사",    rom: "insa",                id: "salam",                               cat: "ekspresi" },
  { kr: "예절",    rom: "yejeol",              id: "tata krama",                          cat: "ekspresi" },
  { kr: "상대",    rom: "sangdae",             id: "pihak lain / lawan bicara",           cat: "benda" },
  { kr: "상대방", rom: "sangdaebang",         id: "pihak lawan bicara",                  cat: "benda" },
  { kr: "존경",    rom: "jonggyeong",          id: "penghormatan",                        cat: "benda" },
  { kr: "반가움", rom: "bangaum",             id: "rasa senang",                         cat: "benda" },
  { kr: "자신",    rom: "jasin",               id: "diri sendiri",                        cat: "benda" },
  { kr: "나이",    rom: "nai",                 id: "umur",                                cat: "benda" },
  { kr: "지위",    rom: "jiwi",                id: "status / kedudukan",                  cat: "benda" },
  { kr: "숙이다", rom: "sukida",              id: "menundukkan",                         cat: "kerja" },
  { kr: "굽히다", rom: "gupida",              id: "membungkukkan",                       cat: "kerja" },
  { kr: "흔들다", rom: "heundeulda",          id: "melambaikan / mengayunkan",           cat: "kerja" },
  { kr: "받치다", rom: "batchida",            id: "menopang",                            cat: "kerja" },
  { kr: "악수",    rom: "aksu",                id: "jabat tangan",                        cat: "benda" },
  { kr: "나타내다", rom: "natanaeda",           id: "menunjukkan",                         cat: "kerja" },
  { kr: "방식",    rom: "bangsik",             id: "cara (metode)",                       cat: "benda" },
  { kr: "상황",    rom: "sanghwang",           id: "situasi",                             cat: "benda" },
  { kr: "주로",    rom: "juro",                id: "biasanya",                            cat: "keterangan" },
  { kr: "한편",    rom: "hanpyeon",            id: "di sisi lain",                        cat: "keterangan" },
  { kr: "훨씬",    rom: "hwolssin",            id: "jauh lebih",                          cat: "keterangan" },
  { kr: "공적",    rom: "gongjeok",            id: "formal / resmi",                      cat: "sifat" },
  { kr: "예의",    rom: "yeui",                id: "sopan santun",                        cat: "ekspresi" },
  { kr: "대한",    rom: "daehan",              id: "tentang",                             cat: "keterangan" },
  { kr: "정보",    rom: "jeongbo",             id: "informasi",                           cat: "benda" },
  { kr: "특정",    rom: "teukjeong",           id: "tertentu",                            cat: "sifat" },
  { kr: "추가",    rom: "chuga",               id: "tambahan",                            cat: "benda" },
  { kr: "또한",    rom: "ttohan",              id: "juga (pula)",                         cat: "keterangan" },
  { kr: "다른",    rom: "dareun",              id: "lain",                                cat: "sifat" },
  { kr: "더 이상", rom: "deo isang",           id: "tidak lagi",                          cat: "keterangan" },
  { kr: "이러한", rom: "ireohan",             id: "seperti ini",                         cat: "sifat" },
  { kr: "대부분", rom: "daebubun",            id: "sebagian besar",                      cat: "keterangan" },
  { kr: "지역",    rom: "jiyeok",              id: "wilayah / daerah",                    cat: "tempat" },
  { kr: "사이",    rom: "sai",                 id: "antara",                              cat: "benda" },
  { kr: "가장",    rom: "gajang",              id: "paling",                              cat: "keterangan" },
  { kr: "여러",    rom: "yeoreo",              id: "berbagai",                            cat: "sifat" },
  { kr: "인해",    rom: "inhae",               id: "karena / akibat",                     cat: "keterangan" },
  { kr: "아직",    rom: "ajik",                id: "masih",                               cat: "keterangan" },
  { kr: "모두",    rom: "modu",                id: "semua",                               cat: "keterangan" },
  { kr: "그리고", rom: "geurigo",             id: "dan / lalu",                          cat: "keterangan" },
  { kr: "그래서", rom: "geuraeseo",           id: "jadi",                                cat: "keterangan" },
  { kr: "그러나", rom: "geureona",            id: "tetapi",                              cat: "keterangan" },
  { kr: "진짜",    rom: "jinjja",              id: "benar-benar",                         cat: "keterangan" },
  { kr: "경찰관", rom: "gyeongchalgwan",      id: "petugas polisi",                      cat: "benda" },
  { kr: "소방관", rom: "sobanggwan",          id: "petugas pemadam kebakaran",           cat: "benda" },
  { kr: "공무원", rom: "gongmuwon",           id: "pegawai negeri",                      cat: "benda" },
  { kr: "점원",    rom: "jeomwon",             id: "kasir / pelayan toko",                cat: "benda" },
  { kr: "간호사", rom: "ganhosa",             id: "perawat",                             cat: "benda" },
  { kr: "요리사", rom: "yorisa",              id: "koki",                                cat: "benda" },
  { kr: "운전기사", rom: "unjeongisa",          id: "sopir",                               cat: "benda" },
  { kr: "기술자", rom: "gisulja",             id: "teknisi",                             cat: "benda" },
  { kr: "어부",    rom: "eobu",                id: "nelayan",                             cat: "benda" },
  { kr: "알뜰",    rom: "alttteul",            id: "hemat",                               cat: "sifat" },
  { kr: "생필품", rom: "saengpilpum",         id: "kebutuhan sehari-hari",               cat: "benda" },
  { kr: "구입하다", rom: "guiphada",            id: "membeli (formal)",                    cat: "kerja" },
  { kr: "팁",          rom: "tip",                 id: "tips",                                cat: "benda" },
  { kr: "대형",    rom: "daehyeong",           id: "besar (skala besar)",                 cat: "sifat" },
  { kr: "종종",    rom: "jongjong",            id: "sering",                              cat: "keterangan" },
  { kr: "특가",    rom: "teukga",              id: "harga spesial",                       cat: "benda" },
  { kr: "할인",    rom: "harin",               id: "diskon",                              cat: "benda" },
  { kr: "행사",    rom: "haengsa",             id: "acara / event",                       cat: "benda" },
  { kr: "식료품", rom: "sikryopum",           id: "bahan makanan",                       cat: "benda" },
  { kr: "용품",    rom: "yongpum",             id: "peralatan",                           cat: "benda" },
  { kr: "다양한", rom: "dayanghan",           id: "beragam",                             cat: "sifat" },
  { kr: "상품",    rom: "sangpum",             id: "produk",                              cat: "benda" },
  { kr: "싸다",    rom: "ssada",               id: "murah",                               cat: "sifat" },
  { kr: "판매하다", rom: "panmaehada",          id: "menjual (formal)",                    cat: "kerja" },
  { kr: "마트",    rom: "mateu",               id: "supermarket (mart)",                  cat: "tempat" },
  { kr: "나누어 주다", rom: "nanueo juda",         id: "membagikan",                          cat: "kerja" },
  { kr: "전단지", rom: "jeondanji",           id: "brosur",                              cat: "benda" },
  { kr: "금액",    rom: "geumaek",             id: "jumlah uang",                         cat: "benda" },
  { kr: "추천",    rom: "chucheon",            id: "rekomendasi",                         cat: "benda" },
  { kr: "온라인", rom: "onrain",              id: "online",                              cat: "sifat" },
  { kr: "쇼핑몰", rom: "syopingmol",          id: "pusat belanja",                       cat: "tempat" },
  { kr: "쇼핑",    rom: "syoping",             id: "belanja",                             cat: "kerja" },
  { kr: "정기적으로", rom: "jeonggijeogeuro",     id: "secara rutin",                        cat: "keterangan" },
  { kr: "정기",    rom: "jeonggi",             id: "berkala / tetap",                     cat: "sifat" },
  { kr: "쿠폰",    rom: "kupon",               id: "kupon",                               cat: "benda" },
  { kr: "제공하다", rom: "jegonghada",          id: "menyediakan",                         cat: "kerja" },
  { kr: "활용하다", rom: "hwaryonghada",        id: "memanfaatkan",                        cat: "kerja" },
  { kr: "가전제품", rom: "gajeonjepum",         id: "peralatan elektronik",                cat: "benda" },
  { kr: "가구",    rom: "gagu",                id: "furnitur",                            cat: "benda" },
  { kr: "중고",    rom: "junggo",              id: "barang bekas",                        cat: "sifat" },
  { kr: "거래",    rom: "georae",              id: "transaksi",                           cat: "kerja" },
  { kr: "직거래", rom: "jikgeorae",           id: "transaksi langsung",                  cat: "kerja" },
  { kr: "이루다", rom: "iruda",               id: "membentuk / membuat",                 cat: "kerja" },
  { kr: "이용하다", rom: "iyonghada",           id: "menggunakan (formal)",                cat: "kerja" },
  { kr: "거래하다", rom: "georaehada",          id: "berdagang",                           cat: "kerja" },
  { kr: "택배",    rom: "taekbae",             id: "jasa pengiriman",                     cat: "benda" },
  { kr: "도시",    rom: "dosi",                id: "kota",                                cat: "tempat" },
  { kr: "특별시", rom: "teukbyeolsi",         id: "kota khusus",                         cat: "tempat" },
  { kr: "특별자치시", rom: "teukbyeoljachisi",    id: "kota otonomi khusus",                 cat: "tempat" },
  { kr: "광역시", rom: "gwangyeoksi",         id: "kota metropolitan",                   cat: "tempat" },
  { kr: "수도권", rom: "sudogwon",            id: "wilayah ibu kota",                    cat: "tempat" },
  { kr: "교통",    rom: "gyotong",             id: "transportasi",                        cat: "benda" },
  { kr: "대중교통", rom: "daejunggyotong",      id: "transportasi umum",                   cat: "benda" },
  { kr: "지나다", rom: "jinada",              id: "melewati",                            cat: "kerja" },
  { kr: "이어지다", rom: "ieojida",             id: "berlanjut",                           cat: "kerja" },
  { kr: "조선",    rom: "joseon",              id: "galangan kapal",                      cat: "tempat" },
  { kr: "산업",    rom: "saneop",              id: "industri",                            cat: "benda" },
  { kr: "섬유",    rom: "seomyu",              id: "tekstil",                             cat: "benda" },
  { kr: "발달하다", rom: "baldalhada",          id: "berkembang",                          cat: "kerja" },
  { kr: "공업 도시", rom: "gongeop dosi",        id: "kota industri",                       cat: "tempat" },
  { kr: "규모",    rom: "gyumo",               id: "skala",                               cat: "benda" },
  { kr: "한국인", rom: "hangugin",            id: "orang Korea",                         cat: "negara" },
  { kr: "좌식 문화", rom: "jwasik munhwa",       id: "budaya duduk di lantai",              cat: "benda" },
  { kr: "좌식",    rom: "jwasik",              id: "duduk di lantai",                     cat: "sifat" },
  { kr: "문화",    rom: "munhwa",              id: "budaya",                              cat: "benda" },
  { kr: "현대",    rom: "hyeondae",            id: "modern",                              cat: "sifat" },
  { kr: "전통",    rom: "jeontong",            id: "tradisi",                             cat: "benda" },
  { kr: "온돌",    rom: "ondol",               id: "sistem pemanas lantai tradisional",   cat: "benda" },
  { kr: "난방",    rom: "nanbang",             id: "pemanas",                             cat: "benda" },
  { kr: "시스템", rom: "siseutem",            id: "sistem",                              cat: "benda" },
  { kr: "모이다", rom: "moida",               id: "berkumpul",                           cat: "kerja" },
  { kr: "아파트", rom: "apateu",              id: "apartemen",                           cat: "tempat" },
  { kr: "가까운", rom: "gakkaun",             id: "dekat",                               cat: "sifat" },
  { kr: "개인",    rom: "gaein",               id: "individu",                            cat: "benda" },
  { kr: "종교",    rom: "jonggyo",             id: "agama",                               cat: "benda" },
  { kr: "존중되다", rom: "jonjungdoeda",        id: "dihormati",                           cat: "kerja" },
  { kr: "예수님", rom: "yesunim",             id: "Jesus",                               cat: "benda" },
  { kr: "부처님", rom: "bucheonim",           id: "Buddha",                              cat: "benda" },
  { kr: "탄생일", rom: "tansaengil",          id: "hari kelahiran",                      cat: "waktu" },
  { kr: "크리스마스", rom: "keuriseumaseu",       id: "Natal",                               cat: "waktu" },
  { kr: "기념하다", rom: "ginyeomhada",         id: "memperingati",                        cat: "kerja" },
  { kr: "쓰이다", rom: "sseuida",             id: "digunakan",                           cat: "kerja" },
  { kr: "축하하다", rom: "chukhahada",          id: "merayakan / mengucapkan selamat",     cat: "kerja" },
  { kr: "일어나다", rom: "ireonada",            id: "terjadi",                             cat: "kerja" },
  { kr: "양력",    rom: "yangnyeok",           id: "kalender Masehi",                     cat: "waktu" },
  { kr: "음력",    rom: "eumnyeok",            id: "kalender lunar",                      cat: "waktu" },
  { kr: "기준",    rom: "gijun",               id: "standar / patokan",                   cat: "benda" },
  { kr: "표시하다", rom: "pyosihada",           id: "menandai",                            cat: "kerja" },
  { kr: "일정",    rom: "iljeong",             id: "jadwal",                              cat: "waktu" },
  { kr: "광복절", rom: "gwangbokjeol",        id: "Hari Kemerdekaan Korea",              cat: "waktu" },
  { kr: "한글날", rom: "hangeullal",          id: "Hari Hangul",                         cat: "waktu" },
  { kr: "국경일", rom: "gukgyeongil",         id: "hari nasional",                       cat: "waktu" },
  { kr: "공휴일", rom: "gonghyuil",           id: "hari libur resmi",                    cat: "waktu" },
  { kr: "명절",    rom: "myeongjeol",          id: "hari raya tradisional",               cat: "waktu" },
  { kr: "설날",    rom: "seollal",             id: "Tahun Baru Imlek Korea",              cat: "waktu" },
  { kr: "추석",    rom: "chuseok",             id: "Hari Panen (Chuseok)",                cat: "waktu" },
  { kr: "새해",    rom: "saehae",              id: "tahun baru",                          cat: "waktu" },
];

WORDS.push.apply(WORDS, WORDS_EXTRA2);

// Extra batch: ID cards & immigration, government & industry, transport, society.
const WORDS_EXTRA3 = [
  { kr: "등록증",     rom: "deungnokjeung",        id: "kartu registrasi",                cat: "benda" },
  { kr: "외국인",     rom: "oegugin",              id: "orang asing",                     cat: "benda" },
  { kr: "국적",       rom: "gukjeok",              id: "kewarganegaraan",                 cat: "benda" },
  { kr: "성별",       rom: "seongbyeol",           id: "jenis kelamin",                   cat: "benda" },
  { kr: "생년월일",   rom: "saengnyeonwolil",      id: "tanggal lahir",                   cat: "benda" },
  { kr: "발급일",     rom: "balgeub-il",           id: "tanggal penerbitan",              cat: "benda" },
  { kr: "직업",       rom: "jigeop",               id: "pekerjaan (istilah formal)",      cat: "benda" },
  { kr: "비자",       rom: "bija",                 id: "visa",                            cat: "benda" },
  { kr: "출입국",     rom: "churipguk",            id: "imigrasi (keluar-masuk negara)",  cat: "benda" },
  { kr: "어휘",       rom: "eohwi",                id: "kosakata",                        cat: "benda" },
  { kr: "나라 이름",  rom: "nara ireum",           id: "nama negara",                     cat: "benda" },
  { kr: "직업명",     rom: "jigeopmyeong",         id: "nama pekerjaan",                  cat: "benda" },
  { kr: "자기소개",   rom: "jagisogae",            id: "perkenalan diri",                 cat: "benda" },
  { kr: "관계있다",   rom: "gwangye-itda",         id: "berhubungan",                     cat: "sifat" },
  { kr: "빈칸",       rom: "binkan",               id: "kotak kosong",                    cat: "benda" },
  { kr: "물음",       rom: "mureum",               id: "pertanyaan (bentuk singkat)",     cat: "tanya" },
  { kr: "남",         rom: "nam",                  id: "pria (bentuk singkat/formal)",    cat: "benda" },
  { kr: "여",         rom: "yeo",                  id: "wanita (bentuk singkat/formal)",  cat: "benda" },
  { kr: "제스처",     rom: "jeseucheo",            id: "gesture / gerakan tubuh",         cat: "benda" },
  { kr: "발음",       rom: "bareum",               id: "pelafalan",                       cat: "benda" },
  { kr: "표현",       rom: "pyohyeon",             id: "ekspresi",                        cat: "benda" },
  { kr: "대화하다",   rom: "daehwahada",           id: "berdialog",                       cat: "kerja" },
  { kr: "생활",       rom: "saenghwal",            id: "kehidupan",                       cat: "benda" },
  { kr: "통하다",     rom: "tonghada",             id: "melalui / terhubung",             cat: "kerja" },
  { kr: "플랫폼",     rom: "peullaetpeom",         id: "platform",                        cat: "benda" },
  { kr: "이르다",     rom: "ireuda",               id: "mencapai",                        cat: "kerja" },
  { kr: "대한민국",   rom: "daehanminguk",         id: "Republik Korea",                  cat: "negara" },
  { kr: "정치",       rom: "jeongchi",             id: "politik",                         cat: "benda" },
  { kr: "경제",       rom: "gyeongje",             id: "ekonomi",                         cat: "benda" },
  { kr: "관문",       rom: "gwanmun",              id: "gerbang",                         cat: "tempat" },
  { kr: "인천국제공항", rom: "incheongukjegonghang", id: "Bandara Internasional Incheon",  cat: "tempat" },
  { kr: "인천항",     rom: "incheonhang",          id: "Pelabuhan Incheon",               cat: "tempat" },
  { kr: "부산항",     rom: "busanhang",            id: "Pelabuhan Busan",                 cat: "tempat" },
  { kr: "세계적",     rom: "segyejeok",            id: "mendunia",                        cat: "sifat" },
  { kr: "중화학 산업", rom: "junghwahak saneop",   id: "industri petrokimia",             cat: "benda" },
  { kr: "지방",       rom: "jibang",               id: "daerah",                          cat: "tempat" },
  { kr: "예술",       rom: "yesul",                id: "seni",                            cat: "benda" },
  { kr: "행정",       rom: "haengjeong",           id: "administrasi",                    cat: "benda" },
  { kr: "업무",       rom: "eopmu",                id: "tugas",                           cat: "benda" },
  { kr: "효율적",     rom: "hyoyuljeok",           id: "efisien",                         cat: "sifat" },
  { kr: "수행하다",   rom: "suhaenghada",          id: "melaksanakan",                    cat: "kerja" },
  { kr: "위해",       rom: "wihae",                id: "untuk",                           cat: "keterangan" },
  { kr: "만들어지다", rom: "mandeureojida",        id: "dibentuk / dibuat",               cat: "kerja" },
  { kr: "행정중심복합도시", rom: "haengjeongjungsimbokhapdosi", id: "kota administrasi terpadu", cat: "tempat" },
  { kr: "교육부",     rom: "gyoyukbu",             id: "Kementerian Pendidikan",          cat: "benda" },
  { kr: "고용노동부", rom: "goyongnodongbu",       id: "Kementerian Tenaga Kerja",        cat: "benda" },
  { kr: "부처",       rom: "bucheo",               id: "departemen",                      cat: "benda" },
  { kr: "경부선",     rom: "gyeongbuseon",         id: "Jalur Kereta Api Gyeongbu",       cat: "tempat" },
  { kr: "호남선",     rom: "honamseon",            id: "Jalur Kereta Api Honam",          cat: "tempat" },
  { kr: "과학",       rom: "gwahak",               id: "ilmu pengetahuan",                cat: "benda" },
  { kr: "소통",       rom: "sotong",               id: "komunikasi",                      cat: "benda" },
  { kr: "유대감",     rom: "yudaegam",             id: "rasa kebersamaan / ikatan emosional", cat: "benda" },
  { kr: "형성하다",   rom: "hyeongseonghada",      id: "membentuk",                       cat: "kerja" },
  { kr: "도움",       rom: "doum",                 id: "bantuan",                         cat: "benda" },
  { kr: "취하다",     rom: "chwihada",             id: "mengambil",                       cat: "kerja" },
  { kr: "가지다",     rom: "gajida",               id: "memiliki",                        cat: "kerja" },
  { kr: "지속되다",   rom: "jisokdoeda",           id: "berlanjut (terus-menerus)",       cat: "kerja" },
  { kr: "순환시키다", rom: "sunhwansikida",        id: "mensirkulasikan / mengalirkan",   cat: "kerja" },
  { kr: "깔다",       rom: "kkalda",               id: "memasang",                        cat: "kerja" },
  { kr: "뜨겁다",     rom: "tteugeopda",           id: "panas",                           cat: "sifat" },
  { kr: "사용되다",   rom: "sayongdoeda",          id: "dipakai",                         cat: "kerja" },
  { kr: "정부",       rom: "jeongbu",              id: "pemerintah",                      cat: "benda" },
  { kr: "기관",       rom: "gigan",                id: "lembaga",                         cat: "benda" },
  { kr: "법정",       rom: "beopjeong",            id: "resmi menurut hukum",             cat: "keterangan" },
  { kr: "고객님",     rom: "gogaengnim",           id: "pelanggan (bentuk sangat sopan)", cat: "benda" },
  { kr: "문자",       rom: "munja",                id: "pesan teks",                      cat: "benda" },
  { kr: "해프닝",     rom: "haepuning",            id: "kejadian tak terduga",            cat: "benda" }
];

WORDS.push.apply(WORDS, WORDS_EXTRA3);

// Every answer option must have a Korean counterpart for the reveal labels.
WORDS.forEach(function (w) {
  if (!KO[w.id]) KO[w.id] = w.kr;
});
